# Generated by Django 4.0.6 on 2022-08-20 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('time', models.DateTimeField(verbose_name=datetime.datetime.now)),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room',
            new_name='name',
        ),
    ]
