# Generated by Django 4.0.6 on 2022-08-20 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_message_rename_room_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='time',
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
