# Generated by Django 4.0.6 on 2022-08-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_message_message_alter_message_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='value',
            field=models.CharField(default=False, max_length=1000000),
            preserve_default=False,
        ),
    ]
